[editor]
tab-width = 4
line-numbers = "absolute"
git-branch-symbol = "î‚ "

[theme]
theme = "ayu"

[keymap.normal]
h = "move_left"
j = "move_down"
k = "move_up"
l = "move_right"
left = "move_left"
down = "move_down"
up = "move_up"
right = "move_right"
home = "line_start"
end = "line_end"
"cmd+home" = "file_start"
"cmd+end" = "file_end"
"cmd+left" = "word_left"
"cmd+right" = "word_right"
"cmd+up" = "move_line_up"
"cmd+down" = "move_line_down"
"cmd+l" = "toggle_line_numbers"
"cmd+b" = "branch_picker"
"ctrl+home" = "file_start"
"ctrl+end" = "file_end"
"ctrl+a" = "file_start"
"ctrl+e" = "file_end"
pgup = "page_up"
pgdn = "page_down"
i = "enter_insert"
":" = "enter_command"
u = "undo"
U = "redo"
"ctrl+c" = "quit"
"ctrl+r" = "redo"
tab = "indent"
"shift+tab" = "unindent"
"cmd+a" = "select_all"
n = "search_next"
N = "search_prev"
"/" = "search_forward"
"?" = "search_backward"

[keymap.insert]
esc = "enter_normal"
left = "move_left"
down = "move_down"
up = "move_up"
right = "move_right"
home = "line_start"
end = "line_end"
"cmd+home" = "file_start"
"cmd+end" = "file_end"
"cmd+left" = "word_left"
"cmd+right" = "word_right"
"cmd+up" = "move_line_up"
"cmd+down" = "move_line_down"
"cmd+l" = "toggle_line_numbers"
"cmd+b" = "branch_picker"
"ctrl+home" = "file_start"
"ctrl+end" = "file_end"
"ctrl+a" = "file_start"
"ctrl+e" = "file_end"
pgup = "page_up"
pgdn = "page_down"
backspace = "backspace"
enter = "newline"
tab = "indent"
"shift+tab" = "unindent"
"cmd+a" = "select_all"
